name: fisqui_bot
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.0.0
  ionicons: ^0.2.2
  line_icons: ^2.0.3
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/